-- MySQL Script generated by MySQL Workbench
-- Mon Jan 16 20:52:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RepairService
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RepairService` ;

-- -----------------------------------------------------
-- Schema RepairService
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RepairService` DEFAULT CHARACTER SET utf8 ;
USE `RepairService` ;

-- -----------------------------------------------------
-- Table `RepairService`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Employees` (
  `EmployeeID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Sector` VARCHAR(45) NULL,
  `HireDate` VARCHAR(45) NULL,
  `Salary` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Customers` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Services` (
  `ServiceID` INT NOT NULL AUTO_INCREMENT,
  `ServiceType` VARCHAR(45) NULL,
  `ServicePrice` INT NULL,
  PRIMARY KEY (`ServiceID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Devices` (
  `DeviceID` INT NOT NULL AUTO_INCREMENT,
  `DeviceType` VARCHAR(45) NULL,
  `Brand` VARCHAR(45) NULL,
  PRIMARY KEY (`DeviceID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Vendor` (
  `VendorID` INT NOT NULL AUTO_INCREMENT,
  `VendorName` VARCHAR(45) NULL,
  `ContactName` VARCHAR(45) NULL,
  `ContactPhone` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`VendorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Inventory_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Inventory_Items` (
  `InventoryItemID` INT NOT NULL AUTO_INCREMENT,
  `ItemName` VARCHAR(45) NULL,
  `Cost` DECIMAL(10,2) NULL,
  `VendorID` INT NOT NULL,
  PRIMARY KEY (`InventoryItemID`),
 
  CONSTRAINT `fk_Vendor_Items_Vendor1`
    FOREIGN KEY (`VendorID`)
    REFERENCES `RepairService`.`Vendor` (`VendorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Repairs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Repairs` (
  `RepairID` INT NOT NULL AUTO_INCREMENT,
  `CustomerID` INT NOT NULL,
  `EmployeeID` INT NOT NULL,
  `ServiceID` INT NOT NULL,
  `DeviceID` INT NOT NULL,
  `VendorItemID` INT NOT NULL,
  `RepairDate` VARCHAR(45) NULL,
  PRIMARY KEY (`RepairID`),

  CONSTRAINT `fk_Repairs_Services1`
    FOREIGN KEY (`ServiceID`)
    REFERENCES `RepairService`.`Services` (`ServiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Repairs_Devices1`
    FOREIGN KEY (`DeviceID`)
    REFERENCES `RepairService`.`Devices` (`DeviceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Repairs_Vendor_Items1`
    FOREIGN KEY (`VendorItemID`)
    REFERENCES `RepairService`.`Inventory_Items` (`InventoryItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Repairs_Customers1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `RepairService`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Repairs_Employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `RepairService`.`Employees` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Payment_Method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Payment_Method` (
  `PaymentMethodID` INT NOT NULL AUTO_INCREMENT,
  `PaymentMethodName` VARCHAR(45) NULL,
  PRIMARY KEY (`PaymentMethodID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Payment` (
  `PaymentID` INT NOT NULL AUTO_INCREMENT,
  `PaymentDate` VARCHAR(45) NULL,
  `Amount` INT NULL,
  `PaymentMethodID` INT NOT NULL,
  PRIMARY KEY (`PaymentID`),
  
  CONSTRAINT `fk_Payment_Payment_Method1`
    FOREIGN KEY (`PaymentMethodID`)
    REFERENCES `RepairService`.`Payment_Method` (`PaymentMethodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Invoices` (
  `InvoiceID` INT NOT NULL AUTO_INCREMENT,
  `InvoiceDate` VARCHAR(45) NULL,
  `RepairID` INT NOT NULL,
  `Cost` INT NULL,
  `PaymentID` INT NOT NULL,
  PRIMARY KEY (`InvoiceID`),

  CONSTRAINT `fk_Invoices_Repairs1`
    FOREIGN KEY (`RepairID`)
    REFERENCES `RepairService`.`Repairs` (`RepairID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Payment1`
    FOREIGN KEY (`PaymentID`)
    REFERENCES `RepairService`.`Payment` (`PaymentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairService`.`Repair_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepairService`.`Repair_Details` (
  `Repair_DetailsID` INT NOT NULL AUTO_INCREMENT,
  `RepairID` INT NOT NULL,
  `PartUsed` VARCHAR(45) NOT NULL,
  `Cost` DECIMAL(10,2) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`Repair_DetailsID`),
  
  CONSTRAINT `fk_Repair_Details_Repairs1`
    FOREIGN KEY (`RepairID`)
    REFERENCES `RepairService`.`Repairs` (`RepairID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
